spring.application.name=Pensieve

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pensieve_db
spring.datasource.username=root
spring.datasource.password=root
# Hibernate settings
spring.jpa.hibernate.ddl-auto=update